#!/usr/bin/env node

// Because uvu is bad in diffing objects
// TODO get rid of uvu?

import fs from 'node:fs'
import child_process from 'node:child_process'
import os from 'node:os'
import path from 'node:path'

const actual = []
const expected = []

for (const l of fs.readFileSync(0, 'utf-8').split('\n')) {
  const line = l.trim()
  if (line === 'Actual:' || line === 'Expected:') {
  } else if (line.startsWith('--')) {
    actual.push(line.slice(2))
  } else if (line.startsWith('++')) {
    expected.push(line.slice(2))
  } else if (actual.length || expected.length) {
    function writeTempFile(prefix, lines) {
      const filePath = path.join(os.tmpdir(), `my-diff-${prefix}.txt`)
      fs.writeFileSync(filePath, lines.join('\n'), 'utf8')
      return filePath
    }

    const actualFile = writeTempFile('actual', actual)
    const expectedFile = writeTempFile('expected', expected)

    try {
      child_process.execSync(
        `git --no-pager diff --no-index --color=always --unified=100000 ${actualFile} ${expectedFile}`,
        { stdio: "inherit" }
      )
    } finally {
      fs.unlinkSync(actualFile)
      fs.unlinkSync(expectedFile)
      actual.length = 0
      expected.length = 0
    }
  }
}
