/**
 * Concatenates all truthy classnames with the space separator.
 * 
 * @param classNames - Classnames to concatenate
 * @returns Concatenated string
 * 
 * @example
 * ```tsx
 * // The result classname will be `'button button-0'` if
 * // large` is truthy, or `'button'` otherwise.
 * <button className={ cc(
 *   'button' satisfies Css<{
 *     border: 'unset'
 *   }>,
 *   large && 'button-0' satisfies Css<{
 *     fontSize: '1.4em'
 *   }>,
 * ) }/>
 * ```
 */
export function cc(...classNames: (undefined | null | string | boolean | number)[]) {
  return classNames.filter(Boolean).join(' ')
}

type ClassesObject<Props> = {
  _?: string
} & {
  [K in keyof Props]?: PropToClasses<Props[K]>
}

type PropToClasses<Val> = Val extends string ? { [k in Val]?: string }
  : Val extends number ? { [k in Val]?: string }
  : Val extends boolean ? string | { true?: string, false?: string }
  : never

/**
 * Selects classnames from `classesObject` based on `props`. Works together with "object notation".
 * 
 * @param props - Props object to select classnames
 * @param classesObject - Classnames object containing the following entries:
 *   - `_` - if present, always selected
 *   - `key: { val1: 'class1', val2: 'class2' }` - if present, selects `'class1'`
 *     if `props.key === 'val1'`, or `'class2'` if `props.key === 'val2'`
 *   - `key: 'class'` - if present, selects `'class'` if `props.key` is truthy
 *   - `key: { true: 'class1', false: 'class2' }` - if present, selects `'class1'`
 *     if `props.key` is truthy, or `'class2'` if `props.key` is falsy
 * @example
 * ```tsx
 * // The result classname will be `'button button-0'` if
 * // `large` is truthy, or `'button'` otherwise.
 * <button className={ co(
 *   {large},
 *   {
 *     // Classnames are generated by Typique plugin
 *     _: 'button',
 *     large: 'button-large',
 *   } satisfies Css<{
 *     // Root CSS props are associated with the first key: `_`
 *     border: 'unset'
 *     // `$large` references the classname by key `large`
 *     '.$large': {
 *       fontSize: '1.4em'
 *     }
 *   }>,
 * ) }/>
 *
 * // True / false notation allows defining styles for both truthy and falsy values
 * <button className={ co(
 *   {large},
 *   {
 *     // Classnames are generated by Typique plugin
 *     _: 'button',
 *     large: {
 *       true: 'button-large-true',
 *       false: 'button-large-false',
 *     },
 *   } satisfies Css<{
 *     border: 'unset'
 *     // `$large$true` references the classname by key `large.true`
 *     '.$large$true': {
 *       fontSize: '1.4em'
 *     }
 *     // `$large$false` references the classname by key `large.false`
 *     '.$large$false': {
 *       fontSize: '1em'
 *     }
 *   }>,
 * ) }/>
 * 
 * // The next example selects based on prop value, e.g.
 * // if `size` is `'large'`, the result classname will be `'button button-large'`.
 * <button className={ co(
 *   {size},
 *   {
 *     // Classnames are generated by Typique plugin
 *     _: 'button',
 *     size: {
 *       small: 'button-small',
 *       large: 'button-large',
 *     },
 *   } satisfies Css<{
 *     border: 'unset'
 *     // `$size$small` references the classname by path `size.small`
 *     '.$size$small': {
 *       fontSize: '.8em'
 *     }
 *     '.$size$large': {
 *       fontSize: '1.4em'
 *     }
 *   }>,
 * ) }/>
 * 
 * ```
 */
export function co<Props extends Record<string, unknown>>(props: Props, classesObject: ClassesObject<Props>): string {
  function selectClass(classesKey: string) {
    const classesVal = classesObject[classesKey]
    if (!classesVal)
      return

    if (classesKey === '_')
      return classesVal

    const propsVal = props[classesKey]
    if (typeof classesVal === 'object' && (typeof propsVal === 'string' || typeof propsVal === 'number'))
      return (classesVal as Record<string | number, string>)[propsVal]

    // boolean
    if (typeof classesVal === 'string' && propsVal)
      return classesVal

    if (typeof classesVal === 'object')
      return (classesVal as Record<'true' | 'false', string>)[propsVal ? 'true' : 'false']
  }

  return Object.keys(classesObject)
    .map(selectClass)
    .filter(c => c && typeof c === 'string')
    .join(' ')
}
